version: '3'
services:
  main-service:
    build:
      context: .
      dockerfile: Dockerfile.main
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq

  googlesheet-service:
    build:
      context: ./services/googlesheetservice
      dockerfile: Dockerfile.googlesheet
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: atlandb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: may13@1993
    ports:
      - "5432:5432"
  
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
